### ISSUE TITLE
firefox? other alternatives

### ISSUE THREAD

**Issue by Sa-Ja-Di** [joey04/xulBlock-Advanced#15]
Why switching to Firefox - Mozilla is anti diverse, anti customization, anti power users - and especially anti-choice..

You should consider more browsers like Vivaldi, Otter or Falkon, which have much more honest and caring developers.

There are lot of anti customization Mozilla trolls around which openly persuade people to give up on customizable browsers. Please be careful in which developers and which advice givers you put your faith into.

Mozilla is the enemy of everything what is unique. So supporting them.. well...

Anyway, just a small suggestion.

**Comment by joey04** [comment]
The reality is that _every_ browser fork is dependent on one of 3 companies: Google, Apple, or Mozilla. Any Apple WebKit fork is of course limited to Apple's platforms. So that means for the vast majority of forks it's either Google or Mozilla as upstream.

So if you want to use Chromium with a custom GUI (like the 3 options Sajadi suggests) by all means go for it. 

But for me it's an easy choice. I have a 14 year history with Firefox, and I strongly prefer Gecko and some other important facets of Mozilla's browser to Chromium.

Plus, of the 4 major browser vendors (including proprietary Microsoft), the least unlikeable is Mozilla. (And I say that knowing full well its many shortcomings and mistakes, like the Brendan Eich fiasco, Mr. Robot, and the lousy way they jerked around add-on devs with e10s and then WebExt.)
